import { z } from 'zod';

export const approverGroupSchema = z.object({
  approver_group_key: z.string(),
  principal_type: z.enum(['external_directory_group', 'atlassian_group', 'email_list']),
  principal_ref: z.string(),
  display_name: z.string(),
  quorum_rule: z.enum(['one_of', 'all_of', 'n_of_m']),
  quorum_value: z.number().int().positive().nullable().optional(),
  escalation_group_key: z.string().nullable().optional(),
  active: z.boolean().default(true),
  notes: z.string().nullable().optional(),
});

export const publicationPolicySchema = z.object({
  publication_policy_key: z.string(),
  description: z.string(),
  approval_required: z.boolean(),
  create_mode: z.enum(['current_page', 'draft_only']),
  update_mode: z.enum(['none', 'managed_sections', 'full_page']),
  publish_after_approval: z.boolean(),
  max_pages_per_operation: z.number().int().positive(),
  diff_required: z.boolean(),
  rollback_allowed: z.boolean(),
  default_publish_parent_strategy: z.enum([
    'default_parent_page_id',
    'ai_inbox_page_id',
    'target_page_or_default_parent',
  ]),
  default_labels: z.array(z.string()).default([]),
  default_content_properties: z.record(z.string(), z.unknown()).default({}),
  notes: z.string().nullable().optional(),
});

export const scopeRegistrySchema = z.object({
  scope_id: z.string(),
  enabled: z.boolean(),
  environment: z.enum(['prod', 'staging', 'dev']),
  tenant_id: z.string(),
  scope_kind: z.enum(['internal_domain', 'client_project', 'territory_program']),
  chatgpt_project_slug: z.string(),
  knowledge_app_slug: z.string(),
  publisher_app_slug: z.string(),
  atlassian_site: z.string(),
  confluence_space_key: z.string(),
  confluence_space_id: z.string().nullable().optional(),
  root_page_id: z.string(),
  default_parent_page_id: z.string(),
  ai_inbox_page_id: z.string(),
  approver_group_key: z.string(),
  publication_policy_key: z.string(),
  identity_mode: z.enum(['managed_scope', 'user_context']),
  write_target_mode: z.enum(['append_only', 'managed_sections', 'full_page']),
  read_cql_guard: z.string(),
  allowed_doc_types: z.array(z.string()).default([]),
  allowed_template_ids: z.array(z.string()).default([]),
  required_labels: z.array(z.string()).default([]),
  forbidden_labels: z.array(z.string()).default([]),
  owner_ref: z.string().nullable().optional(),
  notes: z.string().nullable().optional(),
});

export const initialRegistryYamlSchema = z.object({
  schema_version: z.string(),
  generated_at: z.string().optional(),
  publication_policies: z.array(z.object({
    publication_policy_key: z.string(),
    description: z.string(),
    approval_required: z.boolean(),
    create_mode: z.enum(['current_page', 'draft_only']),
    update_mode: z.enum(['none', 'managed_sections', 'full_page']),
    publish_after_approval: z.boolean(),
    max_pages_per_operation: z.number().int().positive(),
    diff_required: z.boolean(),
    rollback_allowed: z.boolean(),
    default_publish_parent_strategy: z.enum([
      'default_parent_page_id',
      'ai_inbox_page_id',
      'target_page_or_default_parent',
    ]),
    default_labels_csv: z.string().optional().default(''),
    default_content_properties_json: z.string().optional().default('{}'),
    notes: z.string().optional(),
  })),
  approver_groups: z.array(z.object({
    approver_group_key: z.string(),
    principal_type: z.enum(['external_directory_group', 'atlassian_group', 'email_list']),
    principal_ref: z.string(),
    display_name: z.string(),
    quorum_rule: z.enum(['one_of', 'all_of', 'n_of_m']),
    quorum_value: z.number().int().positive().nullable().optional(),
    escalation_group_key: z.string().optional().default(''),
    active: z.boolean().default(true),
    notes: z.string().optional(),
  })),
  scope_registry: z.array(z.object({
    scope_id: z.string(),
    enabled: z.boolean().default(true),
    environment: z.enum(['prod', 'staging', 'dev']),
    tenant_id: z.string(),
    scope_kind: z.enum(['internal_domain', 'client_project', 'territory_program']),
    chatgpt_project_slug: z.string(),
    knowledge_app_slug: z.string(),
    publisher_app_slug: z.string(),
    atlassian_site: z.string(),
    confluence_space_key: z.string(),
    confluence_space_id: z.string().optional().default(''),
    root_page_id: z.string(),
    default_parent_page_id: z.string(),
    ai_inbox_page_id: z.string(),
    approver_group_key: z.string(),
    publication_policy_key: z.string(),
    identity_mode: z.enum(['managed_scope', 'user_context']),
    write_target_mode: z.enum(['append_only', 'managed_sections', 'full_page']),
    read_cql_guard: z.string(),
    allowed_doc_types_csv: z.string().optional().default(''),
    allowed_template_ids_csv: z.string().optional().default(''),
    required_labels_csv: z.string().optional().default(''),
    forbidden_labels_csv: z.string().optional().default(''),
    owner_ref: z.string().optional(),
    notes: z.string().optional(),
  })),
});

export type ApproverGroupRecord = z.infer<typeof approverGroupSchema>;
export type PublicationPolicyRecord = z.infer<typeof publicationPolicySchema>;
export type ScopeRegistryRecord = z.infer<typeof scopeRegistrySchema>;
export type InitialRegistryYaml = z.infer<typeof initialRegistryYamlSchema>;
